### ISSUE TITLE
Colorization papers

### ISSUE THREAD

**Issue by mihaibujanca** [kjw0612/awesome-deep-vision#44]
There is some recent work on colorizing monochrome images:
[Colorful Image Colorization](http://arxiv.org/pdf/1603.08511.pdf) Richard Zhang, Phillip Isola, Alexei A. Efros, ECCV 2016
https://github.com/richzhang/colorization

Ryan Dahl 
http://tinyclouds.org/colorize/

I'm not sure where should this go, or if there should be a separate section for it - I can submit a PR once you let me know

**Comment by kjw0612** [comment]
i guess it belongs to low-level vision, other applications.
