### ISSUE TITLE
Papers in human pose estimation

### ISSUE THREAD

**Issue by ZheC** [kjw0612/awesome-deep-vision#71]
Could you add a list of papers in human pose estimation? I think this is an important topic which is useful for human activity recognition, human motion prediction and human dynamics modelling. There is also a new keypoints challenge for the human pose estimation task in MSCOCO.

**Comment by flynnmd** [comment]
I think that's a good idea, I've also been looking for more human pose work.

@ZheC we could start by adding your ECCV paper/demo :)

**Comment by myungsub** [comment]
Many of our paper sections are quite outdated by now. We would be really grateful if you could send a PR with a list of human pose estimation papers that you currently have :)

**Comment by ZheC** [comment]
Thanks, I definitely have few suggestions on recent papers (Reverse Chronological Order), let me know if you want to know more good papers in this area before the deep learning era: 
1. Cao, Zhe, et al. "Realtime Multi-Person 2D Pose Estimation using Part Affinity Fields." Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition. 2017.
2. Pishchulin, Leonid, et al. "Deepcut: Joint subset partition and labeling for multi person pose estimation." Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition. 2016.
3. Wei, Shih-En, et al. "Convolutional pose machines." Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition. 2016.
4. Newell, Alejandro, Kaiyu Yang, and Jia Deng. "Stacked hourglass networks for human pose estimation." European Conference on Computer Vision. Springer International Publishing, 2016.
5. Pfister, Tomas, James Charles, and Andrew Zisserman. "Flowing convnets for human pose estimation in videos." Proceedings of the IEEE International Conference on Computer Vision. 2015.
6. Tompson, Jonathan J., et al. "Joint training of a convolutional network and a graphical model for human pose estimation." Advances in neural information processing systems. 2014.

**Comment by myungsub** [comment]
Thanks for the list. I agree that the papers you suggest are indeed very important ones in human pose estimation. I've added them on the readme.

**Comment by cbsudux** [comment]
Hi, I've curated a collection of papers and resources on Human Pose estimation : [https://github.com/cbsudux/awesome-human-pose-estimation](https://github.com/cbsudux/awesome-human-pose-estimation). 
Cheers.
